-- Auto-generated from info/amulet_bonus_matrix_draft.json
-- Amulet unique fixed bonuses (34 templates, base_grade=0)

UPDATE item_base_templates SET secondary_bonus_type='crit_chance_pct', secondary_bonus_value=0.005, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Торговый амулет' AND tier=1 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='merchant_discount_flat', fixed_bonus_value=1.0 WHERE name='Амулет купца' AND tier=2 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='magic_find_pct', secondary_bonus_value=0.015, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Медальон торговца' AND tier=3 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='media_damage_photo_percent', fixed_bonus_value=4.0 WHERE name='Амулет удачи' AND tier=4 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='evade_pct', secondary_bonus_value=0.025, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Счастливый амулет' AND tier=5 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='luck', fixed_bonus_value=3.0 WHERE name='Амулет фортуны' AND tier=6 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='charm', fixed_bonus_value=4.0 WHERE name='Амулет судьбы' AND tier=7 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='media_damage_voice_percent', fixed_bonus_value=8.0 WHERE name='Амулет богини удачи' AND tier=8 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='damage_vs_monster_type_flat:fae', fixed_bonus_value=18.0 WHERE name='Амулет провидца' AND tier=9 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='exp_bonus_pct', secondary_bonus_value=0.05, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет Вселенной' AND tier=10 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='intelligence', fixed_bonus_value=1.0 WHERE name='Магический амулет' AND tier=1 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='magic_damage_flat', fixed_bonus_value=4.0 WHERE name='Амулет мага' AND tier=2 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='media_damage_text_percent', fixed_bonus_value=3.0 WHERE name='Медальон тайн' AND tier=3 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='damage_vs_monster_type_flat:undead', fixed_bonus_value=8.0 WHERE name='Амулет знаний' AND tier=4 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='media_damage_voice_percent', fixed_bonus_value=5.0 WHERE name='Амулет архимага' AND tier=5 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='evade_pct', secondary_bonus_value=0.03, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет пророка' AND tier=6 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='luck', fixed_bonus_value=4.0 WHERE name='Амулет звёзд' AND tier=7 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='damage_vs_monster_type_flat:demon', fixed_bonus_value=16.0 WHERE name='Амулет вечности' AND tier=8 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='media_damage_sticker_percent', fixed_bonus_value=9.0 WHERE name='Амулет бездны' AND tier=9 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='hp_max_pct', secondary_bonus_value=0.05, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет Творения' AND tier=10 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='hp_max_pct', secondary_bonus_value=0.025, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет четырёх стихий' AND tier=4 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='dmg_reduce_pct', secondary_bonus_value=0.0312, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет нисхождения' AND tier=5 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='magic_damage_flat', fixed_bonus_value=22.0 WHERE name='Амулет нижнего договора' AND tier=9 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='gold_bonus_pct', secondary_bonus_value=0.0625, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет торговых дорог' AND tier=10 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='endurance', fixed_bonus_value=1.0 WHERE name='Простой амулет' AND tier=1 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='damage_vs_monster_type_flat:construct', fixed_bonus_value=4.0 WHERE name='Амулет стойкости' AND tier=2 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='melee_damage_flat', fixed_bonus_value=6.0 WHERE name='Медальон воина' AND tier=3 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='dmg_reduce_pct', secondary_bonus_value=0.02, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет защиты' AND tier=4 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='strength', fixed_bonus_value=3.0 WHERE name='Медальон стражника' AND tier=5 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='damage_vs_monster_type_flat:undead', fixed_bonus_value=12.0 WHERE name='Амулет паладина' AND tier=6 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='evade_pct', secondary_bonus_value=0.035, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет хранителя' AND tier=7 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type='hp_max_pct', secondary_bonus_value=0.04, fixed_bonus_type=NULL, fixed_bonus_value=0.0 WHERE name='Амулет бессмертия' AND tier=8 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='damage_flat', fixed_bonus_value=18.0 WHERE name='Амулет титана' AND tier=9 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
UPDATE item_base_templates SET secondary_bonus_type=NULL, secondary_bonus_value=0.0, fixed_bonus_type='luck', fixed_bonus_value=5.0 WHERE name='Амулет богов' AND tier=10 AND item_type='amulet' AND COALESCE(base_grade, 0)=0;
