#!/usr/bin/env python3
"""D2-style assignment: 316 legendary bonuses → 316 base_grade=0 templates."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from scripts.lib.legendary_distribution import (  # noqa: E402
    CURATED,
    assignments_to_json,
    load_bonuses,
    run_assignment,
    write_outputs,
)


def _migration_source(payload: list[dict]) -> str:
    rows_repr = json.dumps(
        [
            (row["name"], row["tier"], row["legendary_bonus_ids"])
            for row in payload
        ],
        ensure_ascii=False,
        indent=4,
    )
    curated_repr = json.dumps(
        {f"{name}|{tier}": keys for (name, tier), keys in CURATED.items()},
        ensure_ascii=False,
        indent=4,
    )
    return f'''"""Assign legendary_bonus_ids to all base_grade=0 item templates.

Revision ID: 0107_legendary_template_distribution
Revises: 0106_activate_text_content_bonuses
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0107_legendary_template_distribution"
down_revision: Union[str, None] = "0106_activate_text_content_bonuses"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (name, tier, legendary_bonus_ids) — generated by scripts/assign_legendary_bonus_distribution.py
_DISTRIBUTION: list[tuple[str, int, list[int]]] = {rows_repr}

_CURATED_SNAPSHOT: dict[str, list[str]] = {curated_repr}


def upgrade() -> None:
    conn = op.get_bind()
    for name, tier, ids in _DISTRIBUTION:
        conn.execute(
            sa.text(
                """
                UPDATE item_base_templates
                SET legendary_bonus_ids = :ids
                WHERE name = :name AND tier = :tier AND COALESCE(base_grade, 0) = 0
                """
            ),
            {{"ids": ids, "name": name, "tier": tier}},
        )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            UPDATE item_base_templates
            SET legendary_bonus_ids = '{{}}'
            WHERE COALESCE(base_grade, 0) = 0
            """
        )
    )
    for name, tier, keys in [
        ("Экскалибур", 10, ["BOSS_SLAYER", "SNIPER_SHOT"]),
        ("Теневое жало", 10, ["MYSTIC_SEVEN", "QUICK_REFLEX"]),
        ("Звёздный лук", 10, ["TYPE_HUNTER", "HUNT_FRENZY"]),
        ("Топор бури", 10, ["WOUND_FURY", "BREAKTHROUGH"]),
        ("Рунный меч", 9, ["GOLD_PULSE", "AFFIX_MASTERY"]),
        ("Серебряная дуга", 9, ["IMMUNITY_BREAKER", "REVENGE_THIRST"]),
        ("Мистерикл", 9, ["PIERCING_SCREAM", "VERBOSITY"]),
        ("Кольцо вечности", 10, ["SURVIVOR_SPIRIT", "RARITY_SYNERGY"]),
        ("Медальон стражника", 5, ["MORNING_RITUAL", "FIRST_DAILY_DUNGEON"]),
    ]:
        ids = []
        for key in keys:
            row = conn.execute(
                sa.text("SELECT id FROM legendary_bonuses WHERE bonus_key = :k"),
                {{"k": key}},
            ).fetchone()
            if row:
                ids.append(int(row[0]))
        if ids:
            conn.execute(
                sa.text(
                    """
                    UPDATE item_base_templates
                    SET legendary_bonus_ids = :ids
                    WHERE name = :name AND tier = :tier AND COALESCE(base_grade, 0) = 0
                    """
                ),
                {{"ids": ids, "name": name, "tier": tier}},
            )
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--migration",
        action="store_true",
        help="Write alembic/versions/0107_legendary_template_distribution.py",
    )
    args = parser.parse_args()

    json_path = write_outputs()
    print(f"Wrote {json_path}")
    print(f"Wrote {json_path.with_suffix('.md')}")

    if args.migration:
        assignments, _ = run_assignment()
        payload = assignments_to_json(
            assignments, {str(b["bonus_key"]): b for b in load_bonuses()}
        )
        mig_path = ROOT / "alembic/versions/0107_legendary_template_distribution.py"
        mig_path.write_text(_migration_source(payload), encoding="utf-8")
        print(f"Wrote {mig_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
