"""Database models."""
from waifu_bot.db.models.player import Player
from waifu_bot.db.models.player_mail import PlayerMail, PlayerMailStatus
from waifu_bot.db.models.hidden_skill import HiddenSkillDefinition, PlayerHiddenSkill
from waifu_bot.db.models.passive_skill import PassiveSkillNode, PlayerPassiveSkill
from waifu_bot.db.models.game_config import GameConfig
from waifu_bot.db.models.waifu import (
    MainWaifu,
    MainWaifuPortraitDraft,
    MainWaifuPortraitVariant,
    MainWaifuPaperdollVariant,
    HiredWaifu,
    WaifuRace,
    WaifuClass,
    WaifuRarity,
)
from waifu_bot.db.models.item import Item, InventoryItem, ItemRarity, ItemType, ItemTemplate, Affix, InventoryAffix, ShopOffer
from waifu_bot.db.models.story_boss import PlayerStoryBossFirstKill, StoryBossDefinition
from waifu_bot.db.models.story_seen import PlayerDungeonStorySeen
from waifu_bot.db.models.dungeon import (
    Dungeon,
    DungeonProgress,
    Monster,
    MonsterAbilityTemplate,
    MonsterAffix,
    MonsterTemplate,
    DungeonPool,
    DungeonPoolEntry,
    DungeonRun,
    DungeonRunMonster,
    DropRule,
)
from waifu_bot.db.models.endless import PlayerDungeonPlus, ItemBase, AffixFamily, AffixFamilyTier
from waifu_bot.db.models.art import ItemArt
from waifu_bot.db.models.guild import Guild, GuildMember, GuildBank
from waifu_bot.db.models.guild_extended import (
    GuildLevelThreshold,
    GuildSkillDefinition,
    GuildSkillLevelRow,
    GuildRaidTemplate,
    GuildRaid,
    GuildRaidParticipant,
    GuildWar,
    GuildMemberContributionWeekly,
    GuildGxpBankDaily,
    GuildWarScoreBankDaily,
    GuildWarStatus,
    GuildRaidStatus,
    GuildWarRowStatus,
    GuildActivityLog,
)
from waifu_bot.db.models.skill import Skill, WaifuSkill
from waifu_bot.db.models.battle import BattleLog
from waifu_bot.db.models.tavern import TavernHireSlot, TavernState
from waifu_bot.db.models.expedition import ExpeditionAffix, ExpeditionSlot, ActiveExpedition
from waifu_bot.db.models.group_dungeon import (
    GDDungeonTemplate,
    PlayerChatFirstSeen,
    PlayerGameAction,
    GDEventTemplate,
    GDCompletion,
)
from waifu_bot.db.models.gd_cycle import (
    GDClassSkill,
    GDCycle,
    GDRegistration,
    GDRound,
    GDActiveEffect,
    GDSkillCooldown,
    GDRewardRow,
)

__all__ = [
    "Player",
    "PlayerMail",
    "PlayerMailStatus",
    "HiddenSkillDefinition",
    "PlayerHiddenSkill",
    "PassiveSkillNode",
    "PlayerPassiveSkill",
    "GameConfig",
    "MainWaifu",
    "MainWaifuPortraitDraft",
    "MainWaifuPortraitVariant",
    "MainWaifuPaperdollVariant",
    "HiredWaifu",
    "WaifuRace",
    "WaifuClass",
    "WaifuRarity",
    "Item",
    "InventoryItem",
    "ItemRarity",
    "ItemType",
    "ItemTemplate",
    "Affix",
    "InventoryAffix",
    "ShopOffer",
    "Dungeon",
    "DungeonProgress",
    "Monster",
    "MonsterAbilityTemplate",
    "MonsterAffix",
    "MonsterTemplate",
    "DungeonPool",
    "DungeonPoolEntry",
    "DungeonRun",
    "DungeonRunMonster",
    "DropRule",
    "StoryBossDefinition",
    "PlayerStoryBossFirstKill",
    "PlayerDungeonStorySeen",
    "PlayerDungeonPlus",
    "ItemBase",
    "AffixFamily",
    "AffixFamilyTier",
    "ItemArt",
    "Guild",
    "GuildMember",
    "GuildBank",
    "GuildLevelThreshold",
    "GuildSkillDefinition",
    "GuildSkillLevelRow",
    "GuildRaidTemplate",
    "GuildRaid",
    "GuildRaidParticipant",
    "GuildWar",
    "GuildMemberContributionWeekly",
    "GuildGxpBankDaily",
    "GuildWarScoreBankDaily",
    "GuildWarStatus",
    "GuildRaidStatus",
    "GuildWarRowStatus",
    "Skill",
    "WaifuSkill",
    "BattleLog",
    "TavernHireSlot",
    "TavernState",
    "ExpeditionAffix",
    "ExpeditionSlot",
    "ActiveExpedition",
    "GDDungeonTemplate",
    "PlayerChatFirstSeen",
    "PlayerGameAction",
    "GDEventTemplate",
    "GDCompletion",
    "GDClassSkill",
    "GDCycle",
    "GDRegistration",
    "GDRound",
    "GDActiveEffect",
    "GDSkillCooldown",
    "GDRewardRow",
]
